<div class="tag_line">
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="welcome">
                    <h3 class="wel_rig"><span class="colored">Bem-vindo(a)</span><span class="colored">:</span> <?php echo $this->user->name; ?> </h3>
                    <div class="wel_mag"><div class="bbread"><a class="subpage_block" href="<?php echo $this->url(array('module' => 'alunos', 'controller' => 'index', 'action' => 'index')); ?>">Área do Aluno</a><div class="subpage_breadcrumbs_dv"></div>Arquivos</div></div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
</div>	

<div class="main_content_area">
    <div class="container ">
        <div class="row">
            <div class="span3">
                <ul class="sub-menu-short short_left">
                    <li><a href="<?php echo $this->url(array('module' => 'alunos', 'controller' => 'index', 'action' => 'index')); ?>">Inicio</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'alunos', 'controller' => 'index', 'action' => 'dados')); ?>">Meus dados</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'alunos', 'controller' => 'index', 'action' => 'perguntas')); ?>">Perguntar ao Professor</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'alunos', 'controller' => 'index', 'action' => 'boletim')); ?>">Minhas Notas e Faltas</a></li> 	
                    <li class="actives" id="dif"><a href="<?php echo $this->url(array('module' => 'alunos', 'controller' => 'index', 'action' => 'arquivos')); ?>">Arquivos</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'alunos', 'controller' => 'index', 'action' => 'sair')); ?>">Sair</a></li>
                </ul>			
            </div>
            <div class="span9">
                <div class="row-fluid">  
                    <?php echo $this->flashMessages(); ?>
                    <br>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Descrição do Arquivo</th>
                                <th>Professor</th>
                                <th>Data da Postagem</th>
                                <th>Opções</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->results as $results): ?>
                            <tr>
                                <td><?php echo $results->description; ?></td>
                                <td><?php echo $results->name; ?></td>
                                <td><?php echo $results->date; ?></td>
                                <td>
                                    <a href="<?php echo $this->baseUrl('/uploads/archives/' . $results->file); ?>">
                                        <span class="label label-info">Baixar Arquivo</span>
                                    </a>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>    
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="divide30"></div>