<div class="tag_line">
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="welcome">
                    <h3 class="wel_rig"><span class="colored">Bem-vindo(a)</span><span class="colored">:</span> <?php echo $this->user->name; ?> </h3>
                    <div class="wel_mag"><div class="bbread"><a class="subpage_block" href="<?php echo $this->url(array('module' => 'alunos', 'controller' => 'index', 'action' => 'index')); ?>">Área do Aluno</a><div class="subpage_breadcrumbs_dv"></div>Notas</div></div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
</div>	

<div class="main_content_area">
    <div class="container ">
        <div class="row">
            <div class="span3">
                <ul class="sub-menu-short short_left">
                    <li><a href="<?php echo $this->url(array('module' => 'alunos', 'controller' => 'index', 'action' => 'index')); ?>">Inicio</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'alunos', 'controller' => 'index', 'action' => 'dados')); ?>">Meus dados</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'alunos', 'controller' => 'index', 'action' => 'perguntas')); ?>">Perguntar ao Professor</a></li>
                    <li class="actives" id="dif"><a href="<?php echo $this->url(array('module' => 'alunos', 'controller' => 'index', 'action' => 'boletim')); ?>">Minhas Notas e Faltas</a></li> 	
                    <li><a href="<?php echo $this->url(array('module' => 'alunos', 'controller' => 'index', 'action' => 'arquivos')); ?>">Arquivos</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'alunos', 'controller' => 'index', 'action' => 'sair')); ?>">Sair</a></li>
                </ul>			
            </div>
            <div class="span9">
                <div class="row-fluid">  
                    <?php echo $this->flashMessages(); ?>
                    <h3 class="title"><span>Minhas Notas:</span></h3>
                    <div class="bs-docs-example servis">
                        <div class="accordion" id="accordion2">
                            <div class="accordion-group">
                                <div class="accordion-heading open_head">
                                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">Módulo 1</a>
                                </div>
                                <div id="collapseOne" class="accordion-body collapse in">
                                    <div class="accordion-inner">
                                        <table class="table table-striped">
                                            <thead>
                                                <tr>
                                                    <th>Discliplina</th>
                                                    <th>N1</th>
                                                    <th>N2</th>
                                                    <th>F</th>
                                                    <th>FJ</th>
                                                    <th>NT</th>
                                                    <th>FT</th>
                                                    <th>NR</th>
                                                    <th>S</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php foreach ($this->mod1 as $modulo1): ?>
                                                <tr>
                                                    <td><?php echo $modulo1->discipline; ?></td>
                                                    <td class="center"><?php echo $modulo1->n_1; ?></td>
                                                    <td class="center"><?php echo $modulo1->n_2; ?></td>
                                                    <td class="center"><?php echo $modulo1->f_n; ?></td>
                                                    <td class="center"><?php echo $modulo1->f_j; ?></td>
                                                    <td class="center"><?php echo $modulo1->n_2+$modulo1->n_1; ?></td>
                                                    <td class="center"><?php echo $modulo1->f_n+$modulo1->f_j; ?></td>
                                                    <td class="center"><?php echo $modulo1->n_r; ?></td>
                                                    <td class="center">
                                                        <?php if ($modulo1->situation == 0): ?>
                                                        <span class="label">Em Andamento</span>
                                                        <?php elseif($modulo1->situation == 1): ?>
                                                        <span class="label label-success">Aprovado</span>
                                                        <?php elseif($modulo1->situation == 2): ?>
                                                        <span class="label label-important">Reprovado</span>
                                                        <?php endif; ?>
                                                    </td>
                                                </tr>
                                                <?php endforeach; ?>
                                            </tbody>
                                        </table>    
                                    </div>
                                </div>
                            </div>
                            <div class="accordion-group">
                                <div class="accordion-heading">
                                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">Módulo 2</a>
                                </div>
                                <div id="collapseTwo" class="accordion-body collapse">
                                    <div class="accordion-inner">
                                        <table class="table table-striped">
                                            <thead>
                                                <tr>
                                                    <th>Discliplina</th>
                                                    <th>N1</th>
                                                    <th>N2</th>
                                                    <th>F</th>
                                                    <th>FJ</th>
                                                    <th>NT</th>
                                                    <th>FT</th>
                                                    <th>NR</th>
                                                    <th>S</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php foreach ($this->mod2 as $modulo2): ?>
                                                <tr>
                                                    <td><?php echo $modulo2->discipline; ?></td>
                                                    <td class="center"><?php echo $modulo2->n_1; ?></td>
                                                    <td class="center"><?php echo $modulo2->n_2; ?></td>
                                                    <td class="center"><?php echo $modulo2->f_n; ?></td>
                                                    <td class="center"><?php echo $modulo2->f_j; ?></td>
                                                    <td class="center"><?php echo $modulo2->n_2+$modulo2->n_1; ?></td>
                                                    <td class="center"><?php echo $modulo2->f_n+$modulo2->f_j; ?></td>
                                                    <td class="center"><?php echo $modulo2->n_r; ?></td>
                                                    <td class="center">
                                                        <?php if ($modulo2->situation == 0): ?>
                                                        <span class="label">Em Andamento</span>
                                                        <?php elseif($modulo2->situation == 1): ?>
                                                        <span class="label label-success">Aprovado</span>
                                                        <?php elseif($modulo2->situation == 2): ?>
                                                        <span class="label label-important">Reprovado</span>
                                                        <?php endif; ?>
                                                    </td>
                                                </tr>
                                                <?php endforeach; ?>
                                            </tbody>
                                        </table>                                
                                    </div>
                                </div>
                            </div>
                            <div class="accordion-group">
                                <div class="accordion-heading">
                                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">Módulo 3</a>
                                </div>
                                <div id="collapseThree" class="accordion-body collapse">
                                    <div class="accordion-inner">
                                        <table class="table table-striped">
                                            <thead>
                                                <tr>
                                                    <th>Discliplina</th>
                                                    <th>N1</th>
                                                    <th>N2</th>
                                                    <th>F</th>
                                                    <th>FJ</th>
                                                    <th>NT</th>
                                                    <th>FT</th>
                                                    <th>NR</th>
                                                    <th>S</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php foreach ($this->mod3 as $modulo3): ?>
                                                <tr>
                                                    <td><?php echo $modulo3->discipline; ?></td>
                                                    <td class="center"><?php echo $modulo3->n_1; ?></td>
                                                    <td class="center"><?php echo $modulo3->n_2; ?></td>
                                                    <td class="center"><?php echo $modulo3->f_n; ?></td>
                                                    <td class="center"><?php echo $modulo3->f_j; ?></td>
                                                    <td class="center"><?php echo $modulo3->n_2+$modulo3->n_1; ?></td>
                                                    <td class="center"><?php echo $modulo3->f_n+$modulo3->f_j; ?></td>
                                                    <td class="center"><?php echo $modulo3->n_r; ?></td>
                                                    <td class="center">
                                                        <?php if ($modulo3->situation == 0): ?>
                                                        <span class="label">Em Andamento</span>
                                                        <?php elseif($modulo3->situation == 1): ?>
                                                        <span class="label label-success">Aprovado</span>
                                                        <?php elseif($modulo3->situation == 2): ?>
                                                        <span class="label label-important">Reprovado</span>
                                                        <?php endif; ?>
                                                    </td>
                                                </tr>
                                                <?php endforeach; ?>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <div class="accordion-group">
                                <div class="accordion-heading">
                                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseFour">Módulo 4</a>
                                </div>
                                <div id="collapseFour" class="accordion-body collapse ">
                                    <div class="accordion-inner">
                                                                                <table class="table table-striped">
                                            <thead>
                                                <tr>
                                                    <th>Discliplina</th>
                                                    <th>N1</th>
                                                    <th>N2</th>
                                                    <th>F</th>
                                                    <th>FJ</th>
                                                    <th>NT</th>
                                                    <th>FT</th>
                                                    <th>NR</th>
                                                    <th>S</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php foreach ($this->mod4 as $modulo4): ?>
                                                <tr>
                                                    <td><?php echo $modulo4->discipline; ?></td>
                                                    <td class="center"><?php echo $modulo4->n_1; ?></td>
                                                    <td class="center"><?php echo $modulo4->n_2; ?></td>
                                                    <td class="center"><?php echo $modulo4->f_n; ?></td>
                                                    <td class="center"><?php echo $modulo4->f_j; ?></td>
                                                    <td class="center"><?php echo $modulo4->n_2+$modulo4->n_1; ?></td>
                                                    <td class="center"><?php echo $modulo4->f_n+$modulo4->f_j; ?></td>
                                                    <td class="center"><?php echo $modulo4->n_r; ?></td>
                                                    <td class="center">
                                                        <?php if ($modulo4->situation == 0): ?>
                                                        <span class="label">Em Andamento</span>
                                                        <?php elseif($modulo4->situation == 1): ?>
                                                        <span class="label label-success">Aprovado</span>
                                                        <?php elseif($modulo4->situation == 2): ?>
                                                        <span class="label label-important">Reprovado</span>
                                                        <?php endif; ?>
                                                    </td>
                                                </tr>
                                                <?php endforeach; ?>
                                            </tbody>
                                        </table>                
                                    </div>
                                </div>
                            </div>
                        </div>
                        <script type="text/javascript">
                            jQuery(function($) {
                                $(".accordion-toggle").click(function() {
                                    if ($(this).parent().hasClass("open_head"))
                                    {
                                        $(this).parent().toggleClass("open_head");
                                    }
                                    else
                                    {
                                        $(".open_head").removeClass("open_head");
                                        $(this).parent().toggleClass("open_head");
                                    }
                                });
                            });
                        </script>
                    </div> 
                </div>
            </div>
        </div>
    </div>
</div>
<div class="divide30"></div>