<div class="tag_line">
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="welcome">
                    <h3 class="wel_rig"><span class="colored">Bem-vindo(a)</span><span class="colored">:</span> <?php echo $this->results->name; ?> </h3>
                    <div class="wel_mag"><div class="bbread"><a class="subpage_block" href="<?php echo $this->url(array('module' => 'professores', 'controller' => 'index', 'action' => 'index')); ?>">Área do Professor</a><div class="subpage_breadcrumbs_dv"></div>Lançar Notas</div></div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
</div>	

<div class="main_content_area">
    <div class="container ">
        
        <?php if ($this->entry == '00:00:00' or is_null($this->entry)): ?>
        <div class="alert alert-error"<b>Você ainda não marcou seu ponto hoje!</b> <a href="<?php echo $this->url(array('module' => 'professores', 'controller' => 'index', 'action' => 'ponto')); ?>"><b><span class="label label-important">Clique aqui</span></b></a> para marcar sua entrada.</div>
        <?php elseif ($this->exit == '00:00:00' or is_null($this->exit)): ?>
        <div class="alert alert-info"<b>Você a sua saida hoje!</b> <a href="<?php echo $this->url(array('module' => 'professores', 'controller' => 'index', 'action' => 'ponto')); ?>"><b><span class="label label-info">Clique aqui</span></b></a> para marcar sua saida.</div>
        <?php endif; ?>
        
        <div class="row">
            <div class="span3">
                <ul class="sub-menu-short short_left">
                    <li><a href="<?php echo $this->url(array('module' => 'professores', 'controller' => 'index', 'action' => 'index')); ?>">Inicio</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'professores', 'controller' => 'index', 'action' => 'dados')); ?>">Meus dados</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'professores', 'controller' => 'index', 'action' => 'perguntas')); ?>">Perguntar ao Professor</a></li>
                    <li class="actives" id="dif"><a href="<?php echo $this->url(array('module' => 'professores', 'controller' => 'index', 'action' => 'boletim')); ?>">Lançar Notas e Faltas</a></li> 	
                    <li><a href="<?php echo $this->url(array('module' => 'professores', 'controller' => 'index', 'action' => 'arquivos')); ?>">Arquivos</a></li>
                    <li><a href="http://dopdf.softonic.com.br/download#pathbar" target="_blank">Gerador de PDF</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'professores', 'controller' => 'index', 'action' => 'sair')); ?>">Sair</a></li>
                </ul>			
            </div>
            <div class="span9">
                <div class="row-fluid">  
                    <?php echo $this->flashMessages(); ?>
                    <h3 class="title"><span>Selecione um aluno:</span></h3>
                    <table cellpadding="0" cellspacing="0" border="0" class="display" id="tables" width="100%">
                        <thead>
                            <tr>
                                <th>Nome do Aluno</th>
                                <th>Curso</th>
                                <th>Lançar Nota</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->students as $students): ?>
                                <tr class="gradeX even">
                                    <td><a href="<?php echo $this->url(array('module' => 'professores', 'controller' => 'index', 'action' => 'lancar', 'aluno' => $students->id)); ?>" style="color: #000;"><b><?php echo $students->name; ?></b></a></td>
                                    <td><?php echo $students->course_name; ?></td>
                                    <td class="center">
                                        <a href="<?php echo $this->url(array('module' => 'professores', 'controller' => 'index', 'action' => 'lancar', 'aluno' => $students->id)); ?>">
                                            <span class="label label-important">Lançar Nota</span>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="divide30"></div>
<?php $this->headLink()->appendStylesheet($this->baseUrl('/static/css/demo_page.css'))
        ->appendStylesheet($this->baseUrl('/static/css/demo_table.css'));
?>
<?php $this->headScript()->appendFile($this->baseUrl('/static/js/jquery.dataTables.min.js')); ?>
<?php $this->headScript()->captureStart() ?>
$(document).ready(function() {
$('#tables').dataTable({
"bLengthChange": false,
});
} );
<?php $this->headScript()->captureEnd() ?>