<?php echo $this->headTitle()->prepend('A Escola'); ?>
<div class="tag_line">
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="welcome">
                    <h3 class="wel_rig"><span class="colored">A Escola</span><span class="colored">:</span> Conheça-nos</h3>
                    <div class="wel_mag"><div class="bbread"><a class="subpage_block" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index')); ?>">Inicio</a><div class="subpage_breadcrumbs_dv"></div>A Escola</div></div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
</div> <!-- /tag_line -->

<div class="main_content_area">
    <div class="container">
        <div class="row">
            <div class="span3 ">
                <h3 class="title marg_serch"><span>Saiba Mais</span></h3>	
                <ul class="categories">
                    <li><a href="<?php echo $this->url(array('module' => 'cursos', 'controller' => 'index', 'action' => 'index')); ?>">Nossos Cursos</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'social', 'controller' => 'index', 'action' => 'index')); ?>">Responsabilidade Social</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'contato', 'controller' => 'index', 'action' => 'index')); ?>">Contato Online</a></li>
                </ul>
            </div>
            <div class="span9">
                <div class="marg20">
                    <div class="welcome_sidebar">
                        <div class="wel_cenm"><h3>Centro Tecnológico e Formação Profissional.</h3></div>
                    </div>
                    <p>
                        O <i>"CENTEP – Centro Tecnológico e Formação Profissional"</i> instituição que oferece os Cursos Técnicos em Edificações, Meio Ambiente, Mineração, Patologia Clínica, Química Geral e Segurança do Trabalho.
                    </p>
                    <img src="<?php echo$this->baseUrl('/static/img/turma.jpg'); ?>" alt="Cursos Técnicos"><br><br>
                    <p>
                        Situada em Vespasiano, Minas Gerais vem traçando, com sua Entidade Mantenedora, um caminho educacional desde  2005 visando a implantação de uma Escola com cursos Técnicos nas áreas industrial, meio ambiente e de mineração levando-se em consideração a situação de que Vespasiano faz parte da Região Metropolitana de Belo Horizonte (Capital de Minas Gerais) e tem proximidade com várias outras cidades além de possuir características satisfatórias que indicam demanda e infraestrutura adequadas para realização do Projeto. 
                    </p>
                    <p>
                        Os trabalhos para a criação da Escola tiveram início no mês de julho do mesmo ano e sua sede já havia sido definida, iniciando-se, assim, a estruturação física, administrativa e pedagógica da Instituição. Os processos de Credenciamento da Instituição e de Autorização dos Cursos iniciaram-se no princípio do mês fevereiro de 2006.
                    </p>
                    <p>
                        A Entidade Mantenedora optou em oferecer estes cursos uma vez que a cidade, bem como a região da qual faz parte, é repleta de indústrias e mineradoras. 
                    </p>
                </div>
            </div>
        </div>
    </div>
</div><!-- /main_content_area -->