<?php echo $this->headTitle()->prepend('Responsabilidade Social'); ?>
<div class="tag_line">
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="welcome">
                    <h3 class="wel_rig"><span class="colored">Responsabilidade Social</span></h3>
                    <div class="wel_mag"><div class="bbread"><a class="subpage_block" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index')); ?>">Inicio</a><div class="subpage_breadcrumbs_dv"></div>A Escola</div></div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
</div> <!-- /tag_line -->

<div class="main_content_area">
    <div class="container">
        <div class="row">
            <div class="span3 ">
                <h3 class="title marg"><span>Saiba Mais</span></h3>	
                <ul class="categories">
                    <li><a href="<?php echo $this->url(array('module' => 'cursos', 'controller' => 'index', 'action' => 'index')); ?>">Nossos Cursos</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'escola', 'controller' => 'index', 'action' => 'index')); ?>">Sobre a Escola</a></li>
                    <li><a href="<?php echo $this->url(array('module' => 'contato', 'controller' => 'index', 'action' => 'index')); ?>">Contato Online</a></li>
                </ul>
            </div>
            <div class="span9">
                <div class="marg20">
                    <div class="welcome_sidebar">
                        <div class="wel_cenm"><h3>Compromisso com a Sociedade.</h3></div>
                    </div>
                    <p>
                        O <i>"CENTEP – Centro Tecnológico e Formação Profissional"</i>, sediado à Av. Alfredo Albano da Costa, nº 176, bairro Jardim Itaú, na cidade de Vespasiano – MG, por meio desta, apresenta as vantagens que a criação da Instituição trará para a cidade e região:
                    </p>
                    <ol>
                        <li>A qualificação, habilitação ou capacitação de centenas de trabalhadores que estão atuando nas áreas industriais, mineradoras e do Meio Ambiente sem preencher os requisitos mínimos para tal;</li>
                        <li>A habilitação de centenas de jovens que precisam se ingressar no mercado de trabalho</li>
                        <li>A redução bastante significativa dos custos financeiros para se fazer um dos cursos oferecidos pelo CENTEP, uma vez que a escola que oferece cursos técnicos na cidade atende um número pequeno de alunos frente à demanda da cidade e região</li>
                        <li>A geração de empregos diretos, como os de professores, auxiliares administrativos, serviços gerais e etc, além dos indiretos</li>
                        <li>A arrecadação de impostos municipais</li>
                        <li>O acesso mais fácil às informações sobre segurança, mineração e conservação do meio ambiente visto que, a instituição, através de seus alunos, estará inserindo conhecimento no meio social</li>
                    </ol>
                    <p>A melhoria da qualidade da prestação de serviços diversos por parte dos profissionais mediante o aumento da concorrência por empregos.</p>
                </div>
            </div>
        </div>
    </div>
</div><!-- /main_content_area -->