<?php echo $this->headTitle()->prepend('Editar Conteudos'); ?>

<h1 class="grid_12 margin-top no-margin-top-phone">Editar Conteudos</h1>

<div class="grid_12">
    <?php echo $this->flashMessages(); ?>
</div>

<form action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>" class="grid_12 validate">
    <fieldset>
        <legend>Criar conteudo</legend>
        <div class="row">
            <label for="title">
                <strong>Titulo</strong>
                <small>Defina um titulo para o conteudo</small>
            </label>
            <div>
                <?php echo $this->form->title; ?>
            </div>
        </div>
        <div class="row">
            <label for="text">
                <strong>Conteudo</strong>
                <small>Defina um titulo para o conteudo</small>
            </label>
            <div>
                <?php echo $this->form->text; ?>
            </div>
        </div>
    </fieldset>
    <div class="actions">
        <div class="left">
            <?php echo $this->form->send; ?>
        </div>
    </div>
</form>