<?php echo $this->headTitle()->prepend('Controle de Presença Professores'); ?>

<h1 class="grid_12 margin-top no-margin-top-phone">Controle de Presença Professores</h1>

<div class="grid_12">
    <?php echo $this->flashMessages(); ?>
</div>

<div class="grid_12">
    <a href="<?php echo $this->url(array('module' => 'administrador', 'controller' => 'professores', 'action' => 'adicionar')); ?>" class="button block blue" style="float: right;">
        Adicionar novo Professor
    </a>
</div>

<div class="grid_12">
    <div class="box">
        <div class="header">
            <h2><img class="icon" src="<?php echo $this->baseUrl('/static/img/adm/icons/packs/fugue/16x16/application-list.png'); ?>">Lista de Professores Cadastrados</h2>
        </div>
        <div class="content">
            <table class="dynamic styled" data-filter-Bar="always" data-table-tools='{"display":false}'>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nome</th>
                        <th>Data</th>
                        <th>Entrada</th>
                        <th>Saida</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->results as $results): ?>
                    <tr>
                        <td class="center"><?php echo $results->id; ?></td>
                        <td><?php echo $results->name; ?></td>
                        <?php $date = explode('-', $results->teachers_date); ?>
                        <td class="center"><strong><?php echo $date[2] . '/' . $date[1] . '/' . $date[0] ; ?></strong></td>
                        <td class="center"><strong><?php echo $results->teachers_entry; ?></strong></td>
                         <td class="center"><strong><?php echo $results->teachers_exit; ?></strong></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>